name: Build and Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ '!main' ]

env:
  NODE_VERSION: '20'

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests (if any)
        run: npm test --if-present

      - name: Build application (test build)
        run: |
          echo "🏗️  Starting build process..."
          echo "Working directory: $(pwd)"
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Electron version: $(npx electron --version)"
          
          # Clean any previous builds
          npm run clean
          
          # Run build with debug output
          npm run dist:debug
        env:
          # Don't publish during PR builds
          SKIP_PUBLISH: true
          DEBUG: electron-builder

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-test-${{ matrix.os }}
          path: dist/
          retention-days: 3
